### ISSUE TITLE
fails to flash with no segments

### ISSUE THREAD

**Issue by drahnr** [ferrous-systems/nrfdfu-rs#13]
I am trying to flash a nrf52 dongle w/ the rubble demo https://github.com/jonas-schievink/rubble/tree/044b5370c2b32a73ed47833ab96c1b0cb5a4b797/demos/nrf52-demo

Initially I had trouble with the `nrfutil 6.1.0` which is used by `dongle-flash` from one of the ferrous systems workshops, and hence found this alternative.

So this works fine with `debug` builds where the `elf` info is present, I accidentally made a copy & paste mistake, that included
```
[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false
```

which lead to 

```
error: no loadable program segments found
```

which really should be

```
error: missing debug info, assure your binary is built with `debug=true`
```

which provides some information on what to do

( I :heart:  this tool and a lot of other things you do! )

**Comment by jonas-schievink** [comment]
Thanks for the report!

According the to [Cargo docs](https://doc.rust-lang.org/cargo/reference/profiles.html#overrides), `build-override` applies only to build scripts, proc macros, and their dependencies, so it should have no effect on the resulting binary. Can you provide the ELF binary that reproduces this problem, and possibly also the step you took to build it?

**Comment by drahnr** [comment]
Dummy project to get some active component regulated but provide feedback via blutooth, derived from your rubble demo project.
[wasserschlauch.zip](https://github.com/ferrous-systems/nrfdfu-rs/files/6831584/wasserschlauch.zip)

**Comment by jonas-schievink** [comment]
Both binaries in there fail with `firmware starts at address 0x0, expected 0x1000`, not `no loadable program segments found`.

If I build the rubble nrf52-demo from sources, but using your `.x` file, the resulting binary (built in release mode) works fine, and it also works fine after adding this block to the rubble workspace `Cargo.toml`:

```toml
[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false
```

**Comment by drahnr** [comment]
Mea culpa, I forgot I temporarily flashed it on a DK.

The correct files are:

[wasserschlauch.zip](https://github.com/ferrous-systems/nrfdfu-rs/files/6836856/wasserschlauch.zip)

Double checked and added all the relevant items:

```
cargo b
cargo b --release
cargo run
cargo run --release
nrfdfu target/thumbv7em-none-eabihf/debug/wasserschlauch
nrfdfu target/thumbv7em-none-eabihf/release/wasserschlauch
```

where the last 4 fail with:

```
error: no loadable program segments found
```

**Comment by jonas-schievink** [comment]
I've pushed https://github.com/ferrous-systems/nrfdfu-rs/commit/e9700a580e046b68f2be49627ebe4f42c08c8a5a, which improves the error message in this case – the problem is caused by not passing `-Tlink.x` to the linker, so the linker doesn't know how to assemble the output file and produces essentially an empty file.
