### ISSUE TITLE
Timeouts on Windows 10

### ISSUE THREAD

**Issue by jamesmunns** [ferrous-systems/nrfdfu-rs#9]
We've had a participant run into persistent timeouts when using nrfdfu.

I tried to address this in https://github.com/ferrous-systems/nrfdfu-rs/tree/try-forever, but this did not seem to help.

We should troubleshoot on Win10

**Comment by jonas-schievink** [comment]
Test firmware for debugging this: [known_good_blinky.zip](https://github.com/ferrous-systems/nrfdfu-rs/files/6664547/known_good_blinky.zip)
